name: 'Build ECS App'
on:
  - push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}

    - name: Build image
      id: build-image
      env:
        IMAGE_TAG: ${{ github.sha }}
        DOCKER_BUILDKIT: 1
      run: |
        # Build a docker container
        USER_ID=1001
        GROUP_ID=1001
        export UID=${USER_ID}
        export GID=${GROUP_ID}
        docker build -t opstest:$IMAGE_TAG 
